
baseURL = 'https://693c5fdf901959000848dbed--finalff12.netlify.app/'
languageCode = 'fr-fr'
title = 'MECADO'
theme = []
# Absolute URLs are required for Snipcart validation
relativeURLs = false
canonifyURLs = true
